# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherForecast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!
	
  # Pods for WeatherForecast
	pod 'IQKeyboardManagerSwift'
	pod 'Alamofire'#, '3.5.0'
	pod 'MBProgressHUD'
	pod 'ReachabilitySwift'
	pod 'Toaster'
	pod 'AFDateHelper'
	
  target 'WeatherForecastTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
